#!/bin/bash
# vim: set ts=4 sw=4 et:

BASE=$(cd $(dirname $0);pwd)
pushd $BASE

for f in $(ls)
do
    if [ -d $f ] ; then
        echo "### $f ###"
        pushd "$f"
        git co master
        git pull
        popd
    fi
done

popd
