#!/bin/bash
# vim: set ts=4 sw=4 et:

BASE=$(cd $(dirname $0);pwd)
pushd $BASE

for f in $(ls)
do
    if [ -d $f ] ; then
        echo -e "\n### $f ###"
        pushd "$f" > /dev/null
        git co master
        git pull
        popd > /dev/null
    fi
done

popd
