#!/bin/bash

case "$TERM" in
linux)
  export LC_MESSAGES=C
  ;;
*)
  export LANG=ja_JP.UTF-8
  export TERM='screen-256color'
  export DISPLAY=localhost:0.0
  ;;
esac

export EDITOR=vim

# Source original definitions
if [[ -f /etc/skel/.bashrc ]] ; then
  . /etc/skel/.bashrc
fi

if [[ -f ~/.bash_aliases ]] ; then
  . ~/.bash_aliases
fi

if [[ -d "$TOOLBOX_DIR" ]]; then
  [[ -s "$TOOLBOX_DIR/share/git-core/contrib/completion/git-completion.bash" ]] && \
      . "$TOOLBOX_DIR/share/git-core/contrib/completion/git-completion.bash"
  [[ -s "$TOOLBOX_DIR/share/git-core/contrib/completion/git-prompt.sh" ]] && \
      . "$TOOLBOX_DIR/share/git-core/contrib/completion/git-prompt.sh"
  PG_="\[\e[4;31m\]\$(__git_ps1)"
  GIT_PS1_SHOWDIRTYSTATE=true
fi
PB_="\[\e[0;33m\]=> \$?\n"
P1_="\[\e[4;32m\]\$(date +'%F %T %z') "
P2_="\[\e[36m\]\u@\h:"
P3_="\[\e[35m\]\w"
PE_="\[\e[0m\]\n\\\$ "
export PS1=$PB_$P1_$P2_$P3_$PG_$PE_

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] &&
    . "$SDKMAN_DIR/bin/sdkman-init.sh"

# This loads nvm
export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] &&
    . "$NVM_DIR/nvm.sh"
[[ -s "$NVM_DIR/bash_completion" ]] &&
    . "$NVM_DIR/bash_completion"

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] &&
    . "$HOME/.rvm/scripts/rvm"
:

# vim: set ft=sh ts=2 sw=2 et:
