#
# usage: ansible-playbook mklink.yml -i hosts
#
- hosts: localhost
  connection: local
  tasks:
    - name: シンボリックリンク作成
      file: src=.dotfiles/_{{item}} dest=~/.{{item}} state=link
      with_items:
        - bash_aliases
        - bash_profile
        - bashrc
        - gitconfig
        - gitexclude
        - hgrc
        - tmux.conf
        - vim
        - vimrc

# vim: set ts=2 sw=2 et:
