#
# usage: ansible-playbook mklink.yml -i hosts
#
- hosts: localhost
  connection: local
  tasks:
    - name: Create a symbolic link
      file: src=.dotfiles/_{{item}} dest=~/.{{item}} state=link
      with_items:
        - bash_aliases
        - gitconfig
        - gitexclude
        - tigrc
        - tmux.conf
        - vim

# vim: set ft=yaml ts=2 sw=2 et:
