[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_symbols_ascii = 1
let g:airline_powerline_fonts = 0
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme = 'dark'
let g:airline_section_c = "%{expand('%:~:gs?\\?/?')} %M"
if has('iconv')
  let g:airline_section_z = '[0x%{FencB()}] %#__accent_bold#(%v,%l)/%L%#__restore__#%6P'
else
  let g:airline_section_z =                '%#__accent_bold#(%v,%l)/%L%#__restore__#%6P'
endif
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['nvim-yarp','vim-hug-neovim-rpc']

[[plugins]]
repo= 'prabirshrestha/vim-lsp'

[[plugins]]
repo= 'mattn/vim-lsp-settings'

[[plugins]]
repo= 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo= 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo= 'hrsh7th/vim-vsnip'

[[plugins]]
repo= 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 't9md/vim-textmanip'

[[plugins]]
repo = 'vim-scripts/gtags.vim'
hook_add = '''
let g:gen_tags#gtags_auto_gen = 1
'''

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'cohama/agit.vim'
