[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
source ~/.config/nvim/plugins/LanguageClient-neovim.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_symbols_ascii = 1
let g:airline_powerline_fonts = 0
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme = 'dark'
let g:airline_section_c = "%{expand('%:~:gs?\\?/?')} %M"
if has('iconv')
  let g:airline_section_z = '[0x%{FencB()}] %#__accent_bold#(%v,%l)/%L%#__restore__#%6P'
else
  let g:airline_section_z =                '%#__accent_bold#(%v,%l)/%L%#__restore__#%6P'
endif
'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if   = '''!has('nvim') && has('python3') && system('pip3 show pynvim') != '' '''

[[plugins]]
repo = 'roxma/nvim-yarp'
depends = ['/vim-hug-neovim-rpc']

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['/nvim-yarp','/vim-hug-neovim-rpc']

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 't9md/vim-textmanip'

[[plugins]]
repo = 'vim-scripts/gtags.vim'
hook_add = '''
let g:gen_tags#gtags_auto_gen = 1
'''

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'cohama/agit.vim'
